version: '3.5'

x-traefik-default-labels: &traefik-default-labels
  traefik.backend: BACKEND
  traefik.frontend.rule: "Host:SERVICE.${SERVER_DOMAIN}"
  traefik.port: PORT
  traefik.enable: true
  traefik.docker.network: traefik
  traefik.frontend.headers.SSLRedirect: true
  traefik.frontend.headers.STSSeconds: 315360000
  traefik.frontend.headers.browserXSSFilter: true
  traefik.frontend.headers.contentTypeNosniff: true
  traefik.frontend.headers.forceSTSHeader: true
  traefik.frontend.headers.SSLHost: ${ROOT_DOMAIN}
  traefik.frontend.headers.STSIncludeSubdomains: true
  traefik.frontend.headers.STSPreload: true
  traefik.frontend.headers.frameDeny: true

x-traefik-auth-labels: &traefik-auth-labels
  <<: *traefik-default-labels
  traefik.frontend.auth.basic: ${HTTP_AUTH}

services:
  transmission:
    container_name: transmission
    image: linuxserver/transmission
    restart: unless-stopped
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TIMEZONE}
    volumes:
      - ${CONFIG_PATH}/transmission:/config
      - ${DOWNLOADS_PATH}/watch:/watch
      - ${DOWNLOADS_PATH}:/downloads
    networks:
      - traefik
    labels:
      <<: *traefik-default-labels
      traefik.backend: transmission
      traefik.frontend.rule: "Host:transmission.${SERVER_DOMAIN}"
      traefik.port: 9091

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    restart: unless-stopped
    depends_on:
      - transmission
      - jackett
    ports:
      - "8989:8989"
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
    volumes:
      - ${LOCALTIME_PATH}:/etc/localtime:ro
      - ${CONFIG_PATH}/sonarr:/config
      - ${MEDIA_PATH}:/tv
      - ${DOWNLOADS_PATH}:/downloads
    networks:
      - traefik
    labels:
      <<: *traefik-auth-labels
      traefik.backend: sonarr
      traefik.frontend.rule: "Host:sonarr.${SERVER_DOMAIN}"
      traefik.port: 8989

  radarr:
    container_name: radarr
    image: linuxserver/radarr
    restart: unless-stopped
    depends_on:
      - transmission
      - jackett
    ports:
      - "7878:7878"
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
    volumes:
      - ${LOCALTIME_PATH}:/etc/localtime:ro
      - ${CONFIG_PATH}/radarr:/config
      - ${MEDIA_PATH}:/movies
      - ${DOWNLOADS_PATH}:/downloads
    networks:
      - traefik
    labels:
      <<: *traefik-auth-labels
      traefik.backend: radarr
      traefik.frontend.rule: "Host:radarr.${SERVER_DOMAIN}"
      traefik.port: 8989

  jackett:
    container_name: jackett
    image: linuxserver/jackett
    restart: unless-stopped
    ports:
      - "9117:9117"
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
    volumes:
      - ${LOCALTIME_PATH}:/etc/localtime:ro
      - ${CONFIG_PATH}/jackett:/config
      - ${DOWNLOADS_PATH}:/downloads
    networks:
      - traefik
    labels:
      <<: *traefik-auth-labels
      traefik.backend: jackett
      traefik.frontend.rule: "Host:jackett.${SERVER_DOMAIN}"
      traefik.port: 9117

networks:
  traefik:
    external: true
