version: '3.5'

services:

  transmission:
    container_name: transmission
    image: linuxserver/transmission
    restart: unless-stopped
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TIMEZONE}
    volumes:
      - ${CONFIG_PATH}/transmission:/config
      - ${DOWNLOADS_PATH}/transmission/watch:/watch
      - ${DOWNLOADS_PATH}/transmission:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transmission.rule=Host(`transmission.${SERVER_DOMAIN}`)"
      - "traefik.http.routers.transmission.entrypoints=http"
      - "traefik.http.routers.transmission.middlewares=https-redirect"
      - "traefik.http.routers.transmission-secure.rule=Host(`transmission.${SERVER_DOMAIN}`)"
      - "traefik.http.routers.transmission-secure.service=transmission"
      - "traefik.http.routers.transmission-secure.entrypoints=https"
      - "traefik.http.routers.transmission-secure.tls=true"
      - "traefik.http.routers.transmission-secure.tls.certresolver=letsencrypt"
      - "traefik.http.services.transmission.loadbalancer.server.port=9091"

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    restart: unless-stopped
    depends_on:
      - transmission
      - jackett
    ports:
      - "8989:8989"
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
    volumes:
      - ${LOCALTIME_PATH}:/etc/localtime:ro
      - ${CONFIG_PATH}/sonarr:/config
      - ${LOCAL_MEDIA_PATH}:/tv
      - ${DOWNLOADS_PATH}/transmission:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.${SERVER_DOMAIN}`)"
      - "traefik.http.routers.sonarr.entrypoints=http"
      - "traefik.http.routers.sonarr.middlewares=https-redirect"
      - "traefik.http.routers.sonarr-secure.rule=Host(`sonarr.${SERVER_DOMAIN}`)"
      - "traefik.http.routers.sonarr-secure.service=sonarr"
      - "traefik.http.routers.sonarr-secure.entrypoints=https"
      - "traefik.http.routers.sonarr-secure.middlewares=http-auth"
      - "traefik.http.routers.sonarr-secure.tls=true"
      - "traefik.http.routers.sonarr-secure.tls.certresolver=letsencrypt"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"

  radarr:
    container_name: radarr
    image: linuxserver/radarr
    restart: unless-stopped
    depends_on:
      - transmission
      - jackett
    ports:
      - "7878:7878"
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
    volumes:
      - ${LOCALTIME_PATH}:/etc/localtime:ro
      - ${CONFIG_PATH}/radarr:/config
      - ${LOCAL_MEDIA_PATH}:/movies
      - ${DOWNLOADS_PATH}/transmission:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`radarr.${SERVER_DOMAIN}`)"
      - "traefik.http.routers.radarr.entrypoints=http"
      - "traefik.http.routers.radarr.middlewares=https-redirect"
      - "traefik.http.routers.radarr-secure.rule=Host(`radarr.${SERVER_DOMAIN}`)"
      - "traefik.http.routers.radarr-secure.service=radarr"
      - "traefik.http.routers.radarr-secure.entrypoints=https"
      - "traefik.http.routers.radarr-secure.middlewares=http-auth"
      - "traefik.http.routers.radarr-secure.tls=true"
      - "traefik.http.routers.radarr-secure.tls.certresolver=letsencrypt"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"

  jackett:
    container_name: jackett
    image: linuxserver/jackett
    restart: unless-stopped
    ports:
      - "9117:9117"
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
    volumes:
      - ${LOCALTIME_PATH}:/etc/localtime:ro
      - ${CONFIG_PATH}/jackett:/config
      - ${DOWNLOADS_PATH}:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jackett.rule=Host(`jackett.${SERVER_DOMAIN}`)"
      - "traefik.http.routers.jackett.entrypoints=http"
      - "traefik.http.routers.jackett.middlewares=https-redirect"
      - "traefik.http.routers.jackett-secure.rule=Host(`jackett.${SERVER_DOMAIN}`)"
      - "traefik.http.routers.jakett-secure.service=jakett"
      - "traefik.http.routers.jackett-secure.entrypoints=https"
      - "traefik.http.routers.jackett-secure.middlewares=http-auth"
      - "traefik.http.routers.jackett-secure.tls=true"
      - "traefik.http.routers.jackett-secure.tls.certresolver=letsencrypt"
      - "traefik.http.services.jakett.loadbalancer.server.port=9117"
