version: '3.5'

services:

  plex:
    container_name: plex
    image: plexinc/pms-docker:${PLEX_VERSION}
    restart: unless-stopped
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TIMEZONE}
      PLEX_CLAIM: ${PLEX_CLAIM}
      ADVERTISE_IP: "http://${HOST_IP}:32400/"
    volumes:
      - ${CONFIG_PATH}/plex:/config
      - ${PLEX_TRANSCODING_PATH}:/transcode
      - ${REMOTE_MEDIA_PATH}:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plex.rule=Host(`plex.${SERVER_DOMAIN}`)"
      - "traefik.http.routers.plex.entrypoints=http"
      - "traefik.http.routers.plex.middlewares=https-redirect"
      - "traefik.http.routers.plex-secure.rule=Host(`plex.${SERVER_DOMAIN}`)"
      - "traefik.http.routers.plex-secure.service=plex"
      - "traefik.http.routers.plex-secure.entrypoints=https"
      - "traefik.http.routers.plex-secure.tls=true"
      - "traefik.http.routers.plex-secure.tls.certresolver=letsencrypt"
      - "traefik.http.services.plex.loadbalancer.server.port=32400"

  tautulli:
    container_name: tautulli
    image: linuxserver/tautulli
    restart: unless-stopped
    ports:
      - "8181:8181"
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TIMEZONE}
    volumes:
      - ${CONFIG_PATH}/tautulli:/config
      - ${CONFIG_PATH}/plex/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tautulli.rule=Host(`tautulli.${SERVER_DOMAIN}`)"
      - "traefik.http.routers.tautulli.entrypoints=http"
      - "traefik.http.routers.tautulli.middlewares=https-redirect"
      - "traefik.http.routers.tautulli-secure.rule=Host(`tautulli.${SERVER_DOMAIN}`)"
      - "traefik.http.routers.tautulli-secure.service=tautulli"
      - "traefik.http.routers.tautulli-secure.entrypoints=https"
      - "traefik.http.routers.tautulli-secure.tls=true"
      - "traefik.http.routers.tautulli-secure.tls.certresolver=letsencrypt"
      - "traefik.http.services.tautulli.loadbalancer.server.port=8181"

  ombi:
    container_name: ombi
    image: linuxserver/ombi
    restart: unless-stopped
    ports:
      - "3579:3579"
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TIMEZONE}
    volumes:
      - ${LOCALTIME_PATH}:/etc/localtime:ro
      - ${CONFIG_PATH}/ombi:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ombi.rule=Host(`ombi.${SERVER_DOMAIN}`)"
      - "traefik.http.routers.ombi.entrypoints=http"
      - "traefik.http.routers.ombi.middlewares=https-redirect"
      - "traefik.http.routers.ombi-secure.rule=Host(`ombi.${SERVER_DOMAIN}`)"
      - "traefik.http.routers.ombi-secure.service=ombi"
      - "traefik.http.routers.ombi-secure.entrypoints=https"
      - "traefik.http.routers.ombi-secure.tls=true"
      - "traefik.http.routers.ombi-secure.tls.certresolver=letsencrypt"
      - "traefik.http.services.ombi.loadbalancer.server.port=3579"
