version: '2'
services:
  transmission:
    container_name: transmission
    image: linuxserver/transmission
    restart: unless-stopped
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TIMEZONE}
    volumes:
      - ${TRANSMISSION_CONFIG_PATH}:/config
      - ${DOWNLOADS_PATH}:/downloads

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    restart: unless-stopped
    links:
      - transmission
      - jackett
    ports:
      - "8989:8989"
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
    volumes:
      - ${LOCALTIME_PATH}:/etc/localtime:ro
      - ${SONARR_CONFIG_PATH}:/config
      - ${SHOWS_PATH}:/tv
      - ${DOWNLOADS_PATH}:/downloads

  radarr:
    container_name: radarr
    image: linuxserver/radarr
    restart: unless-stopped
    links:
      - transmission
      - jackett
    ports:
      - "7878:7878"
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
    volumes:
      - ${LOCALTIME_PATH}:/etc/localtime:ro
      - ${RADARR_CONFIG_PATH}:/config
      - ${MOVIES_PATH}:/tv
      - ${DOWNLOADS_PATH}:/downloads

  jackett:
    container_name: jackett
    image: linuxserver/jackett
    restart: unless-stopped
    ports:
      - "9117:9117"
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
    volumes:
      - ${LOCALTIME_PATH}:/etc/localtime:ro
      - ${JACKETT_CONFIG_PATH}:/config
      - ${DOWNLOADS_PATH}:/downloads

  plex:
    container_name: plex
    image: plexinc/pms-docker:${PLEX_VERSION}
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TIMEZONE}
      PLEX_CLAIM: ${PLEX_CLAIM}
    network_mode: host
    volumes:
      - ${PLEX_CONFIG_PATH}:/config
      - ${TRANSCODING_PATH}:/transcode
      - ${MEDIA_PATH}:/data/media
      - ${REMOTE_MEDIA_PATH}:/data/remote

  tautulli:
    container_name: tautulli
    image: linuxserver/tautulli
    restart: unless-stopped
    ports:
      - "8181:8181"
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TIMEZONE}
    volumes:
      - ${TAUTULLI_CONFIG_PATH}:/config

  ombi:
    container_name: ombi
    image: linuxserver/ombi
    restart: unless-stopped
    links:
      - sonarr
      - radarr
      - plex
    ports:
      - "3579:3579"
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TIMEZONE}
    volumes:
      - ${LOCALTIME_PATH}:/etc/localtime:ro
      - ${OMBI_CONFIG_PATH}:/config

  watchtower:
    container_name: watchtower
    image: v2tec/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 4 * * *" --cleanup
