version: '2'
services:
  transmission:
    container_name: transmission
    image: linuxserver/transmission
    ports:
      - "8989:8989"
      - "9091:9091"
      - "51413:51413/udp"
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TIMEZONE}
    volumes:
      -v ${TRANSMISSION_CONFIG_PATH}:/config
      -v ${DOWNLOADS_PATH}:/downloads
    restart: always

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    links:
      - transmission
    ports:
      - "8989:8989"
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
    volumes:
      - ${LOCALTIME_PATH}:/etc/localtime:ro
      - ${SONARR_CONFIG_PATH}:/config
      - ${SHOWS_PATH}:/tv
      - ${DOWNLOADS_PATH}:/downloads
    restart: always

  radarr:
    container_name: radarr
    image: linuxserver/radarr
    links:
      - transmission
    ports:
      - "7878:7878"
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
    volumes:
      - ${LOCALTIME_PATH}:/etc/localtime:ro
      - ${RADARR_CONFIG_PATH}:/config
      - ${MOVIES_PATH}:/tv
      - ${DOWNLOADS_PATH}:/downloads
    restart: always

  plex:
    container_name: plex
    image: linuxserver/plex
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      VERSION: latest
      TZ: ${TIMEZONE}
    network_mode: host
    volumes:
      - ${PLEX_CONFIG_PATH}:/config
      - ${MEDIA_PATH}:/data/media
    restart: always

  plexpy:
    container_name: plexpy
    image: linuxserver/plexpy
    ports:
      - "8181:8181"
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TIMEZONE}
    volumes:
      - ${PLEXPY_CONFIG_PATH}:/config
      - ${PLEX_LOGS_PATH}:/logs:ro
    restart: always

  ombi:
    container_name: ombi
    image: linuxserver/ombi
    ports:
      - "3579:3579"
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TIMEZONE}
    volumes:
      - ${LOCALTIME_PATH}:/etc/localtime:ro
      -v ${OMBI_CONFIG_PATH}:/config
    restart: always
