version: '3.5'

services:

  watchtower:
    container_name: watchtower
    image: v2tec/watchtower
    restart: unless-stopped
    volumes:
      - ${DOCKER_SOCKET}:/var/run/docker.sock
    command: --schedule "0 0 4 * * *" --cleanup

  portainer:
    container_name: portainer
    image: portainer/portainer
    restart: unless-stopped
    command: -H unix:///var/run/docker.sock
    ports:
      - "9000:9000"
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TIMEZONE}
    volumes:
      - ${DOCKER_SOCKET}:/var/run/docker.sock
      - ${CONFIG_PATH}/portainer:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.${SERVER_DOMAIN}`)"
      - "traefik.http.routers.portainer.entrypoints=http"
      - "traefik.http.routers.portainer.middlewares=https-redirect"
      - "traefik.http.routers.portainer-secure.rule=Host(`portainer.${SERVER_DOMAIN}`)"
      - "traefik.http.routers.portainer-secure.entrypoints=https"
      - "traefik.http.routers.portainer-secure.tls=true"
      - "traefik.http.routers.portainer-secure.tls.certresolver=letsencrypt"
      - "traefik.port=9000"

  traefik:
    container_name: traefik
    image: traefik
    restart: unless-stopped
    command:
      - "--api=true"
      - "--entrypoints.http=true"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https=true"
      - "--entrypoints.https.address=:443"
      - "--certificatesresolvers.letsencrypt=true"
      - "--certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=http"
      - "--certificatesresolvers.letsencrypt.acme.email=odarriba@gmail.com"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.watch=true"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ${DOCKER_SOCKET}:/var/run/docker.sock:ro
      - ${CONFIG_PATH}/traefik:/etc/traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${SERVER_DOMAIN}`)"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.middlewares=https-redirect"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.${SERVER_DOMAIN}`)"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.service=api@internal"
      - "traefik.http.routers.traefik-secure.middlewares=http-auth"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=letsencrypt"
      - "traefik.http.middlewares.http-auth.basicauth.users=${HTTP_AUTH}"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "com.centurylinklabs.watchtower.enable=false"
