version: '3.5'

services:
  plex:
    container_name: plex
    image: plexinc/pms-docker:${PLEX_VERSION}
    restart: unless-stopped
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TIMEZONE}
      PLEX_CLAIM: ${PLEX_CLAIM}
      ADVERTISE_IP: "http://${HOST_IP}:32400/"
    volumes:
      - ${PLEX_CONFIG_PATH}:/config
      - ${PLEX_TRANSCODING_PATH}:/transcode
      - ${MEDIA_PATH}:/data
    networks:
      - media-server

  tautulli:
    container_name: tautulli
    image: linuxserver/tautulli
    restart: unless-stopped
    ports:
      - "8181:8181"
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TIMEZONE}
    volumes:
      - ${TAUTULLI_CONFIG_PATH}:/config
      - ${TAUTULLI_LOGS_PATH}:/logs
    networks:
      - media-server

  ombi:
    container_name: ombi
    image: linuxserver/ombi
    restart: unless-stopped
    ports:
      - "3579:3579"
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TIMEZONE}
    volumes:
      - ${LOCALTIME_PATH}:/etc/localtime:ro
      - ${OMBI_CONFIG_PATH}:/config
    networks:
      - media-server

networks:
  media-server:
    external: true
